name: Undeploy from AWS

on:
  workflow_dispatch:

jobs:
  undeploy:
    runs-on: ubuntu-latest

    steps:

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Deregister ECS Task Definition
      run: |
        aws ecs update-service --cluster tdupoiron-cluster --service blackbeard-service --desired-count 0
        aws ecs delete-service --cluster tdupoiron-cluster --service blackbeard-service
